# Generated by Django 3.2.6 on 2021-08-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('married', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
