# Generated by Django 3.2.6 on 2021-09-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='married',
            field=models.CharField(max_length=100),
        ),
    ]
