# Generated by Django 3.2.6 on 2021-09-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0002_alter_form_married'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='last_name',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='married',
            new_name='marry',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='phone_number',
            new_name='number',
        ),
    ]
