# Generated by Django 3.2.6 on 2021-09-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0003_auto_20210902_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='resume',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
