# Generated by Django 3.2.6 on 2021-09-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0004_form_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='resume',
            field=models.FileField(default=None, null=True, upload_to=None),
        ),
    ]
